chartType: line
title: "Shares of total consumption by decile also do not signal an underlying K-shaped economy as shares have remained flat for roughly 20 years."                    
subtitle: "Shares of total expenditure by decile relative to total expenditure"              
xAxisType: temporal
columns:
  x: year
  series: series
  value: value
series_order:
  - Decile 1
  - Decile 5
  - Decile 10
note: "Measures total consumption for each decile relative to total consumption across all deciles for deciles 1, 5, and 10. "
source: "BLS Consumer Expenditure Survey"
data: data.csv
