title: "The evolution of employment dispersion: a replication"
slug: "emp-dispersion-replication"
date: "2026-09-23"
url: ""
figures:
  lfp-quintiles-rf: "Figure 1"
  lfp-quintiles-rf-contemporaneous: "Figure 2"
  unemployment-quintiles-rf: "Figure 3"
  unemployment-quintiles-rf-contemporaneous: "Figure 4"
  lfp-by-education: "Figure 5"
