title: "Inequality in labor force participation has diminished"
slug: "emp-dispersion-graphs"
date: "2026-09-24"
url: ""

figures:
  lfp-by-education: "Figure 1"
  lfp-quintiles-rf: "Figure 2"
  lfp-quintiles-rf-contemporaneous: "Figure 3"
  unemployment-quintiles-rf: "Figure 4"
  unemployment-quintiles-rf-contemporaneous: "Figure 5"
  quintile-characteristics: "Table 1"
