chartType: line
title: " Financial Accounts data from the Federal Reserve shows us that there is more volatility in asset holdings that the CE does not capture."                 
subtitle: "Percent change since 2014, Index: 2014 = 100"

xAxisType: temporal
columns:
  x: year
  series: series
  value: value
series_order:
  - Household income
  - Corporate equities
  - Net worth              
annotations:
  xAxis:
    - { x: "2014" }        
  yAxis:
    - { y: 100 }
 note: "Measures the indexed change in income (measured in the CE) and corporate equities and net worth from the Financial Accounts."           
source: " BLS Consumer Expenditure Survey, Federal Reserve Financial Accounts (S1M.s and S1M.r)"   
data: data.csv
