title: "What we learned about recession indicators, rules, and triggers after the pandemic"
slug: "recession-indicators"
date: "2026-08-10"
url: "https://budgetlab.yale.edu/research/what-we-learned-about-recession-indicators-rules-and-triggers-after-pandemic"
figures:
  sahm-rule: "Figure 1"
  michez-rule: "Figure 2"
  yield-curve: "Figure 3"
  ui-pp: "Figure 4"
  cfnai: "Figure 5"
  news-sentiment: "Figure 6"
  ui-percent: "Appendix Figure 1"
