title: "The labor market looks stable, but low UI claims data should be interpreted carefully"
slug: ui-recipiency
date: "2026-08-04"
url: "https://budgetlab.yale.edu/research/labor-market-looks-stable-low-ui-claims-data-should-be-interpreted-carefully"
figures:
  figure-1-insured-vs-total-unemployment: "FIGURE 1"
  figure-2-long-term-unemployment-share: "FIGURE 2"
  figure-3-indexed-claims-vs-unemployment: "FIGURE 3"
  appendix-figure-1-job-losers-share: "APPENDIX FIGURE 1"
