title: "How to interpret the annual jobs revision "
slug: "ces-qcew-benchmark-revisions"
date: "2026-08-24"
url: "https://budgetlab.yale.edu/research/how-interpret-annual-jobs-revision"
figures:
  revisions-since-2015: "Figure 1"
  final-v-prelim: "Figure 2"
  regressions: "Figure 3"
