title: How Gen X and Millennial parents managed their time
slug: atus-childcare
date: 2026-06-24
url: https://budgetlab.yale.edu/research/how-gen-x-and-millennial-parents-managed-their-time
engineVersion: 1.0.0

figures:
  childcare-by-activity: "Figure 1"
  childcare-by-cohort-all-adults: "Figure 2"
  childcare-by-cohort-parents: "Figure 3"
  work-by-cohort-parents: "Figure 4"
  work-by-youngest-child-age: "Figure 5"
  childcare-by-household-type: "Figure 6"
  work-by-household-type: "Figure 7"
  childcare-by-sex-and-child-age: "Figure 8"
  childcare-by-household-type-and-child-age: "Figure 9"
  leisure-by-cohort: "Appendix Figure 1"
  leisure-by-household-type: "Appendix Figure 2"
