title: "Revenue effects of the tax bill"
slug: tax-bill-revenue-effects
date: 2026-08-15
url: ""

figures:
  total-federal-debt: "Figure 1"
  debt-to-gdp: "Figure 2"
  primary-deficit-to-gdp: "Figure 3"
  total-deficit-to-gdp: "Figure 4"
  tax-cuts-distribution: "Figure 5"
  tax-cuts-distribution-by-income: "Figure 6"
  obbba-tariffs-combined-effects-percent: "Figure 7"
  obbba-tariffs-combined-effects-dollars: "Figure 8"
  estimated-budget-effects: "Table 1"
  budget-effects-by-bill-section: "Table 2"
